# Generated by Django 6.0.2 on 2026-03-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
